Repository codeit-sprint-fullstack/6-sprint-mission-be, pull requests merged in 2025-03, with the labels that each got.

#4 [박민규] sprint 6
  .gitignore
  README.md
  app.js
  jsconfig.json
  package.json
  requests.http
  src/db/prisma/client.prisma.js
  src/db/prisma/migrations/20250320040204_create_article/migration.sql
  src/db/prisma/migrations/20250323050843_/migration.sql
  src/db/prisma/migrations/20250323051232_/migration.sql
  src/db/prisma/migrations/20250323051435_/migration.sql
  src/db/prisma/migrations/20250323051604_/migration.sql
  src/db/prisma/migrations/20250323053532_/migration.sql
  src/db/prisma/migrations/20250323054425_/migration.sql
  src/db/prisma/migrations/20250323054457_/migration.sql
  src/db/prisma/migrations/migration_lock.toml
  src/db/prisma/schema.prisma
  src/middlewares/.gitkeep
  src/modules/articles.js
  src/modules/index.js
  src/modules/products.js
Labels: 매운맛🔥, 최종 제출

#3 [최민경] Sprint6
  .gitignore
  README.md
  package-lock.json
  package.json
  src/db/prisma/client.prisma.js
  src/db/prisma/migrations/20250320082317_initial_commit/migration.sql
  src/db/prisma/migrations/migration_lock.toml
  src/db/prisma/schema.prisma
  src/middleware/errorHandle.middleware.js
  src/models/Items.js
  src/modules/articles.module.js
  src/modules/index.module.js
  src/modules/item.module.js
  src/request.http
  src/server.js
Labels: 최종 제출

#6 [김수경] sprint 7
  .gitignore
  jsconfig.json
  package-lock.json
  package.json
  request.http
  src/app.js
  src/db/prisma/client.prisma.js
  src/db/prisma/migrations/20250318050846_create_article/migration.sql
  src/db/prisma/migrations/20250318053021_create_user/migration.sql
  src/db/prisma/migrations/20250318055151_create_product/migration.sql
  src/db/prisma/migrations/20250318061941_update_product/migration.sql
  src/db/prisma/migrations/20250319111618_create_comment_field/migration.sql
  src/db/prisma/migrations/20250319113417_update_comment_field/migration.sql
  src/db/prisma/migrations/20250320012602_create_on_delete/migration.sql
  src/db/prisma/migrations/20250320014435_create_product_comment_article_comment/migration.sql
  src/db/prisma/migrations/20250320025235_update_fields_attribute/migration.sql
  src/db/prisma/migrations/migration_lock.toml
  src/db/prisma/schema.prisma
  src/modules/articles.module.js
  src/modules/commentsArticle.module.js
  src/modules/commentsProduct.module.js
  src/modules/index.module.js
  src/modules/products.module.js
Labels: 매운맛🔥, 진행 중 🏃

#17 [박민규] 스프린트 7
  .gitignore
  README.md
  app.js
  jsconfig.json
  package.json
  requests.http
  src/db/prisma/client.prisma.js
  src/db/prisma/migrations/20250320040204_create_article/migration.sql
  src/db/prisma/migrations/20250323050843_/migration.sql
  src/db/prisma/migrations/20250323051232_/migration.sql
  src/db/prisma/migrations/20250323051435_/migration.sql
  src/db/prisma/migrations/20250323051604_/migration.sql
  src/db/prisma/migrations/20250323053532_/migration.sql
  src/db/prisma/migrations/20250323054425_/migration.sql
  src/db/prisma/migrations/20250323054457_/migration.sql
  src/db/prisma/migrations/migration_lock.toml
  src/db/prisma/schema.prisma
  src/middlewares/.gitkeep
  src/modules/articles.js
  src/modules/index.js
  src/modules/products.js
Labels: 매운맛🔥, 최종 제출

#11 [이태빈] Sprint7
  .github/pull-request-template.md
  .gitignore
  README.md
  package-lock.json
  package.json
  src/app.js
  src/db/prisma/client.prisma.js
  src/db/prisma/migrations/20250318131126_add_first_table/migration.sql
  src/db/prisma/migrations/20250318145107_add_product_rel/migration.sql
  src/db/prisma/migrations/20250319010554_remove_user_table/migration.sql
  src/db/prisma/migrations/20250320094435_add_tag_tags/migration.sql
  src/db/prisma/migrations/20250320094633_modify_product_table/migration.sql
  src/db/prisma/migrations/20250320171240_add_product_tag_on_delete_cascade/migration.sql
  src/db/prisma/migrations/20250321001436_add_tag_name_unique/migration.sql
  src/db/prisma/migrations/20250321003748_change_on_delete_attribute/migration.sql
  src/db/prisma/migrations/20250321135508_add_user/migration.sql
  src/db/prisma/migrations/migration_lock.toml
  src/db/prisma/mock/articleMock.js
  src/db/prisma/mock/productMock.js
  src/db/prisma/schema.prisma
  src/db/prisma/seed.js
  src/middlewares/handleErrorMiddleware.js
  src/routes/articleRoutes.js
  src/routes/commentRoutes.js
  src/routes/indexRoutes.js
  src/routes/productRoutes.js
  src/routes/userRoutes.js
Labels: 매운맛🔥, 최종 제출

#15 [오하영] Sprint7
  .gitignore
  .http
  jsconfig.json
  package.json
  src/app.js
  src/db/prisma/client.prisma.js
  src/db/prisma/schema.prisma
  src/mock.js
  src/modules/articles.module.js
  src/modules/communityComments.module.js
  src/modules/index.module.js
  src/modules/marketComments.module.js
  src/seed.js
Labels: 최종 제출
