Repository codeit-sprint-fullstack/6-sprint-mission-be, pull requests merged in 2025-05, with the labels that each got.

#16 [이지수B] 미션 7
  .gitignore
  README.md
  constant/ExceptionMessage.js
  openapi.yaml
  package-lock.json
  package.json
  prisma/migrations/20240818182531_/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/mocks/articleMocks.js
  prisma/mocks/comments.js
  prisma/mocks/productMocks.js
  prisma/schema.prisma
  prisma/seed.js
  src/main.js
  src/models/Article.js
  src/models/Comment.js
  src/models/Product.js
  src/prismaClient.js
  src/structs/article/CreateArticleRequestStruct.js
  src/structs/article/GetArticleListRequestStruct.js
  src/structs/article/UpdateArticleRequestStruct.js
  src/structs/comment/CreateCommentRequestStruct.js
  src/structs/comment/GetCommentListRequestStruct.js
  src/structs/comment/UpdateCommentRequestStruct.js
  src/structs/product/CreateProductRequestStruct.js
  src/structs/product/GetProductListRequestStruct.js
  src/structs/product/UpdateProductRequestStruct.js
  src/structs/readme.md
  src/utils/asyncErrorHandler.js
  vercel.json
Labels: 미완성🫠, 진행 중 🏃

#30 [김홍섭] Spring10
  .gitignore
  .vscode/settings.json
  README.md
  article.http
  image.http
  jsconfig.json
  package-lock.json
  package.json
  product.http
  server.js
  src/app.js
  src/config/config.js
  src/controllers/article.controller.js
  src/controllers/auth.controller.js
  src/controllers/comment.controller.js
  src/controllers/image.controller.js
  src/controllers/product.controller.js
  src/controllers/user.controller.js
  src/middlewares/auth.middleware.js
  src/middlewares/error.middleware.js
  src/models/prisma/migrations/20250320040200_create_article/migration.sql
  src/models/prisma/migrations/20250508081835_250508/migration.sql
  src/models/prisma/migrations/migration_lock.toml
  src/models/prisma/prismaClient.js
  src/models/prisma/schema.prisma
  src/repositories/article.repository.js
  src/repositories/auth.repository.js
  src/repositories/comment.repository.js
  src/repositories/image.repository.js
  src/repositories/product.repository.js
  src/repositories/user.repository.js
  src/routes/article.route.js
  src/routes/auth.route.js
  src/routes/comment.route.js
  src/routes/image.route.js
  src/routes/product.route.js
  src/routes/user.route.js
  src/services/article.service.js
  src/services/auth.service.js
  src/services/comment.service.js
  src/services/image.service.js
  src/services/product.service.js
  src/services/user.service.js
  src/utils/apiError.js
  src/utils/catchAsync.js
  swagger.js
  uploads/image-1747013096692.txt
  uploads/image-1747013652496.txt
  uploads/image-1747027480261.png
  uploads/image-1747029740003.png
  user.http
Labels: 매운맛🔥, 진행 중 🏃

#24 [김승준] sprint10
  .gitignore
  .http
  jsconfig.json
  package-lock.json
  package.json
  src/app.js
  src/config/memo
  src/controllers/article.controller.js
  src/controllers/comment.controller.js
  src/controllers/like.controller.js
  src/controllers/product.controller.js
  src/controllers/refreshAccessToken.controller.js
  src/controllers/upload.controller.js
  src/controllers/user.controller.js
  src/db/prisma/client.js
  src/db/prisma/migrations/20250509014833_reset/migration.sql
  src/db/prisma/migrations/20250509020509_add_description_to_product/migration.sql
  src/db/prisma/migrations/20250509020940_add_description_to_producttag/migration.sql
  src/db/prisma/migrations/20250509021524_rename_tag_to_images/migration.sql
  src/db/prisma/migrations/20250509023408_yes/migration.sql
  src/db/prisma/migrations/20250509050111_refresh/migration.sql
  src/db/prisma/migrations/20250513061121_my_log/migration.sql
  src/db/prisma/migrations/20250513061629_mylof/migration.sql
  src/db/prisma/migrations/migration_lock.toml
  src/db/prisma/schema.prisma
  src/middlewares/auth.js
  src/middlewares/error.middleware.js
  src/middlewares/upload.middleware.js
  src/middlewares/validateProductInput.js
  src/routes/article.route.js
  src/routes/comments.route.js
  src/routes/index.js
  src/routes/like.route.js
  src/routes/product.route.js
  src/routes/upload.route.js
  src/routes/user.route.js
  src/utils/customError.js
  src/utils/seed.js
  uploads/1747118042578-670427633.jpg
  uploads/1747124502845-514761944.png
  uploads/1747124502847-867404009.png
  uploads/1747124502848-45436661.jpg
  uploads/1747124660466-492280682.png
  uploads/1747124660469-125953476.png
  uploads/1747124660470-525514704.jpg
  uploads/1747124694658-945142429.jpeg
  uploads/1747124694660-905342169.png
  uploads/1747124694662-186637786.png
  uploads/1747124807376-154736392.jpeg
  uploads/1747124807378-130641241.jpg
  uploads/1747124807379-898073541.png
  uploads/1747124813289-141164050.jpeg
  uploads/1747124813291-489215462.png
  uploads/1747124813331-113504680.jpg
  uploads/1747125558226-677353835.jpg
Labels: 매운맛🔥, 최종 제출

#38 [김수빈]Sprint10
  .env
  .env.example
  .gitignore
  .prettierrc
  .vscode/settings.json
  constant/ExceptionMessage.js
  package-lock.json
  package.json
  prisma/migrations/20240818182531_/migration.sql
  prisma/migrations/20250509003843_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/mocks/articleMocks.js
  prisma/mocks/commentMocks.js
  prisma/mocks/productMocks.js
  prisma/mocks/userMocks.js
  prisma/schema.prisma
  prisma/seed.js
  readme.md
  src/app.js
  src/controllers/articleController.js
  src/controllers/authController.js
  src/controllers/commentController.js
  src/controllers/productController.js
  src/controllers/userController.js
  src/middlewares/HttpError.js
  src/middlewares/authMiddleware.js
  src/middlewares/errorHandler.js
  src/middlewares/imageupload.js
  src/prismaClient.js
  src/repositories/articleRepository.js
  src/repositories/authRepository.js
  src/repositories/commentRepository.js
  src/repositories/productRepository.js
  src/repositories/userRepository.js
  src/routes/articleRouter.js
  src/routes/authRouter.js
  src/routes/commentRouter.js
  src/routes/productRouter.js
  src/routes/userRouter.js
  src/services/OrderService.ㅓㄴ
  src/services/articleService.js
  src/services/authService.js
  src/services/commentService.js
  src/services/productService.js
  src/services/userService.js
  test.http
  uploads/2cd3bbd8-8d65-43d1-ac96-028e1a0114e4.jpg
  uploads/76909ae9-e1d8-4349-a22b-667df8e1b273.png
  uploads/dislikebt-1747184596945.png
  uploads/dislikebt-1747184688755.png
  uploads/ì¦ëªì¬ì§-1747184596943.jpg
  uploads/ì¦ëªì¬ì§-1747184688753.jpg
  vercel.json
Labels: 매운맛🔥, 최종 제출
